#!/usr/bin/env python3
"""Regenerate supabase/functions/_shared/portions.ts from the wizard's portion
list. Run: python3 scripts/gen-portions.py"""
import re
src = open("src/components/wizard/TorahPortions.ts").read()
def phrase(label, cat):
    if cat == "torah":
        return "Parsha " + re.sub(r"^Parshas\s+", "", label).strip()
    if cat == "educational":
        return None
    seg = re.split(r"[–—-]", label, maxsplit=1)[0].strip()
    return "the Book of " + re.sub(r"^(Sefer|Megillas)\s+", "", seg, flags=re.I).strip()
m = {}
for obj in re.finditer(r'\{\s*value:\s*"([^"]+)"[^}]*?\}', src):
    o = obj.group(0)
    val = re.search(r'value:\s*"([^"]+)"', o).group(1)
    lab = re.search(r'label:\s*"([^"]+)"', o)
    cat = re.search(r'category:\s*"([^"]+)"', o)
    if not (lab and cat):
        continue
    p = phrase(lab.group(1), cat.group(1))
    if p is not None:
        m[val] = p
body = ",\n".join(f'  "{k}": "{v}"' for k, v in sorted(m.items()))
open("supabase/functions/_shared/portions.ts", "w").write(
    "// AUTO-GENERATED by scripts/gen-portions.py from\n"
    "// src/components/wizard/TorahPortions.ts — do not edit by hand.\n"
    "// Maps a stored books.torah_portion value to the phrase used in emails:\n"
    '// weekly parshiyos -> "Parsha X"; Nevi\'im/Kesuvim/Megillos/holidays ->\n'
    '// "the Book of X"; middos ("educational") stories are omitted.\n'
    f"const PORTION_PHRASES: Record<string, string> = {{\n{body}\n}};\n\n"
    "export function portionPhrase(value: string | null | undefined): string | null {\n"
    "  if (!value) return null;\n"
    "  return PORTION_PHRASES[value] ?? null;\n"
    "}\n"
)
print("regenerated", len(m), "portions")
