// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Pinned to the current Supabase project (gabrobnkelgxazjibbrm). Build-env
// VITE_SUPABASE_* values may still reference the old, inaccessible project, so
// they must not take precedence. Both values are public/publishable by design.
const SUPABASE_URL = "https://gabrobnkelgxazjibbrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_9YwM5OE70SQBgDYCV26n8g_unnkgxNH";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});