// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfcuzhjtdqbjgawqgcvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmY3V6aGp0ZHFiamdhd3FnY3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyMzM5OTUsImV4cCI6MjA4OTgwOTk5NX0.9zuk69zBjtbwVEaH2Rs1esqXUnDh12iUojc0zdU9Vhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  }
});
