// AUTO-GENERATED by scripts/blog-agent.mjs — do not edit by hand.
// One entry per daily story article; newest first.

import aparshas_ki_savo_for_kids from "./parshas-ki-savo-for-kids.mjs";
import aparshas_ki_seitzei_for_kids from "./parshas-ki-seitzei-for-kids.mjs";
import aparshas_nitzavim_vayeilech_for_kids from "./parshas-nitzavim-vayeilech-for-kids.mjs";
import arosh_hashanah_story_for_kids from "./rosh-hashanah-story-for-kids.mjs";
import asukkos_story_for_kids from "./sukkos-story-for-kids.mjs";
import ayom_kippur_story_for_kids from "./yom-kippur-story-for-kids.mjs";

export const STORY_ARTICLES = [
  aparshas_ki_savo_for_kids,
  aparshas_ki_seitzei_for_kids,
  aparshas_nitzavim_vayeilech_for_kids,
  arosh_hashanah_story_for_kids,
  asukkos_story_for_kids,
  ayom_kippur_story_for_kids,
];
