// AUTO-GENERATED by scripts/blog-agent.mjs — do not edit by hand.
// One entry per daily story article; newest first.

import arosh_hashanah_story_for_kids from "./rosh-hashanah-story-for-kids.mjs";

export const STORY_ARTICLES = [
  arosh_hashanah_story_for_kids,
];
